---
- name: Configure web server
  hosts: testhosts

  vars:
    package_name: httpd
    service_name: httpd

  tasks:
    - name: "Insialling servise {{ package_name }}"
      yum:
        name: "{{ package_name }}"
        state: installed 

    - name: "Running servise {{ package_name }}"
      service: 
        name: "{{ service_name }}"
        state: started
        enabled: yes

    - name: "Create page content"
      copy:
        dest: "/var/www/html/index.html"
        content: "Welcome to my web server\n"

    - name: "Open ports on firewall"
      firewalld:
        port: 80/tcp
        permanent: yes
        state: enabled
        immediate: yes

...
