---
  - name: "Insialling servise {{ package_name }}"
    yum:
      name: "{{ package_name }}"
      state: installed 

  - name: "create content folder"
    file: 
      path: "{{ root }}"
      state: directory
      owner: root
      group: root
    file: 
      path: "{{ root }}/{{ content_folder }}"
      state: directory
      owner: root
      group: root  
      
  - name: "configure servise {{ package_name }}"
    template: src={{ service_name }}.conf dest=/etc/{{ service_name }}/conf/{{ service_name }}.conf owner=root group=root
    notify:
      - restart apache  

  - name: "Running servise {{ package_name }}"
    service: 
      name: "{{ service_name }}"
      state: started
      enabled: yes

  - name: "Create page content"
    template: src=index.html dest={{ root }}/{{ content_folder }}/index.html

  - name: "Open ports on firewall"
    firewalld:
      port: 80/tcp
      permanent: yes
      state: enabled
      immediate: yes

